#!/usr/bin/env node
// Distributes the canonical harness in harness/ to the tool-specific directories
// Claude Code and opencode each read.
//
// harness/ is the only place an agent charter or a skill is edited. The generated
// copies under .claude/ and .opencode/ are committed so the workspace works on a
// fresh clone with no build step, and regenerated by running this script.
//
// Agent charters carry tool-neutral frontmatter. Each tool needs a different subset
// of it, so charters are transformed rather than copied:
//
//   name, description   both tools
//   model-tier          Claude Code only, as `model:` (high -> opus, standard -> sonnet).
//                       opencode resolves the model from opencode.json instead, so that a
//                       workspace pointed at a different provider is not overridden here.
//   claude-tools        Claude Code only, as `tools:`
//   opencode-mode       opencode only, as `mode:`
//   opencode-permission opencode only, as a `permission:` map
//
// Skills and commands are the same format in both tools, so they are copied verbatim.
//
// Anything under .claude/ or .opencode/ that this script does not own is left alone —
// that is how the openspec-generated opsx commands and skills survive a sync.

import { readdirSync, readFileSync, writeFileSync, mkdirSync, rmSync, statSync, existsSync } from "node:fs";
import { join, dirname, relative } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const HARNESS = join(ROOT, "harness");

const MODEL_BY_TIER = { high: "opus", standard: "sonnet" };

const TARGETS = {
  claude: { agents: ".claude/agents", skills: ".claude/skills", commands: ".claude/commands" },
  opencode: { agents: ".opencode/agent", skills: ".opencode/skills", commands: ".opencode/commands" },
};

/** Split a markdown file into its frontmatter block and body. */
function splitFrontmatter(text, path) {
  const match = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/.exec(text);
  if (!match) throw new Error(`${path}: no frontmatter block`);
  return { frontmatter: match[1], body: match[2] };
}

/**
 * Read the flat key/value pairs of a frontmatter block. Values are either inline
 * or a YAML folded block (`>-`), whose continuation lines are indented; folded
 * values are rejoined into one line, which is what both tools expect for a
 * description.
 */
function parseFrontmatter(frontmatter, path) {
  const fields = new Map();
  const lines = frontmatter.split(/\r?\n/);

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (!line.trim()) continue;

    const entry = /^([A-Za-z][A-Za-z0-9_-]*):\s*(.*)$/.exec(line);
    if (!entry) throw new Error(`${path}: cannot parse frontmatter line: ${line}`);

    const [, key, inline] = entry;
    if (inline !== ">-" && inline !== ">" && inline !== "|") {
      fields.set(key, inline.trim());
      continue;
    }

    const folded = [];
    while (i + 1 < lines.length && /^\s+\S/.test(lines[i + 1])) {
      folded.push(lines[++i].trim());
    }
    fields.set(key, folded.join(" "));
  }

  return fields;
}

/** Wrap a long value across continuation lines so the generated file stays readable. */
function foldedValue(key, value, width = 96) {
  const out = [];
  let line = "";
  for (const word of value.split(/\s+/)) {
    if (line && line.length + word.length + 1 > width) {
      out.push(line);
      line = word;
    } else {
      line = line ? `${line} ${word}` : word;
    }
  }
  if (line) out.push(line);
  return out.length > 1
    ? `${key}: >-\n${out.map((l) => `  ${l}`).join("\n")}`
    : `${key}: ${value}`;
}

function require_(fields, key, path) {
  const value = fields.get(key);
  if (!value) throw new Error(`${path}: missing required frontmatter key '${key}'`);
  return value;
}

function renderClaudeAgent(fields, body, path) {
  const head = [
    `name: ${require_(fields, "name", path)}`,
    foldedValue("description", require_(fields, "description", path)),
  ];

  const tools = fields.get("claude-tools");
  if (tools) head.push(`tools: ${tools}`);

  const tier = fields.get("model-tier");
  if (tier) {
    const model = MODEL_BY_TIER[tier];
    if (!model) throw new Error(`${path}: unknown model-tier '${tier}'`);
    head.push(`model: ${model}`);
  }

  return `---\n${head.join("\n")}\n---\n\n${body.trimStart()}`;
}

function renderOpencodeAgent(fields, body, path) {
  const head = [foldedValue("description", require_(fields, "description", path))];

  head.push(`mode: ${fields.get("opencode-mode") ?? "subagent"}`);

  const permission = fields.get("opencode-permission");
  if (permission) {
    const rules = permission
      .split(",")
      .map((pair) => pair.trim())
      .filter(Boolean)
      .map((pair) => {
        const [tool, action] = pair.split("=").map((s) => s.trim());
        if (!tool || !action) throw new Error(`${path}: bad opencode-permission entry '${pair}'`);
        return `  ${tool}: ${action}`;
      });
    head.push(`permission:\n${rules.join("\n")}`);
  }

  return `---\n${head.join("\n")}\n---\n\n${body.trimStart()}`;
}

function copyTree(from, to) {
  mkdirSync(to, { recursive: true });
  for (const entry of readdirSync(from)) {
    const src = join(from, entry);
    const dst = join(to, entry);
    if (statSync(src).isDirectory()) copyTree(src, dst);
    else writeFileSync(dst, readFileSync(src));
  }
}

function syncAgents() {
  const source = join(HARNESS, "agents");
  const written = [];

  for (const target of Object.values(TARGETS)) {
    mkdirSync(join(ROOT, target.agents), { recursive: true });
  }

  for (const file of readdirSync(source).filter((f) => f.endsWith(".md")).sort()) {
    const path = join(source, file);
    const { frontmatter, body } = splitFrontmatter(readFileSync(path, "utf8"), path);
    const fields = parseFrontmatter(frontmatter, path);

    const claudePath = join(ROOT, TARGETS.claude.agents, file);
    writeFileSync(claudePath, renderClaudeAgent(fields, body, path));
    written.push(claudePath);

    const opencodePath = join(ROOT, TARGETS.opencode.agents, file);
    writeFileSync(opencodePath, renderOpencodeAgent(fields, body, path));
    written.push(opencodePath);
  }

  return written;
}

function syncSkills() {
  const source = join(HARNESS, "skills");
  const names = readdirSync(source).filter((d) => statSync(join(source, d)).isDirectory());
  const written = [];

  for (const target of Object.values(TARGETS)) {
    const base = join(ROOT, target.skills);
    mkdirSync(base, { recursive: true });
    for (const name of names) {
      const dst = join(base, name);
      // Replace rather than merge, so a file deleted from harness/ does not linger.
      if (existsSync(dst)) rmSync(dst, { recursive: true, force: true });
      copyTree(join(source, name), dst);
      written.push(dst);
    }
  }

  return written;
}

/**
 * Commands are copied file by file rather than as a tree: both target directories
 * also hold the openspec-generated opsx commands, which this script does not own
 * and must not delete.
 */
function syncCommands() {
  const source = join(HARNESS, "commands");
  if (!existsSync(source)) return [];

  const names = readdirSync(source).filter((f) => f.endsWith(".md")).sort();
  const written = [];

  for (const target of Object.values(TARGETS)) {
    const base = join(ROOT, target.commands);
    mkdirSync(base, { recursive: true });
    for (const name of names) {
      const dst = join(base, name);
      writeFileSync(dst, readFileSync(join(source, name)));
      written.push(dst);
    }
  }

  return written;
}

const files = [...syncAgents(), ...syncSkills(), ...syncCommands()];
for (const file of files) console.log(relative(ROOT, file).replaceAll("\\", "/"));
console.log(`\nSynced ${files.length} paths from harness/ to .claude/ and .opencode/.`);
